### ISSUE TITLE
restful-format middleware can't serialize a root vector

### ISSUE THREAD

**Issue by denisidoro** [macchiato-framework/macchiato-core#33]
Using the restful-format as highlighted [here](https://macchiato-framework.github.io/docs/restful-middleware.html) works for, say:
```clojure
{:message "hello"}
```
but not for 
```clojure
[1 2 3]
```

**Comment by yogthos** [comment]
The middleware is using the following [multimethod](https://github.com/macchiato-framework/macchiato-core/blob/e5ec039ad0c028736c5ecfa21c439bb217813248/src/macchiato/middleware/restful_format.cljs#L45) to serialize responses, and it's not doing anything special regarding maps and vectors handling. If you could investigate a bit more that would be really helpful, otherwise I'll try take a look when I get a chance.

**Comment by denisidoro** [comment]
@yogthos, the problem is with [deserialize-request](https://github.com/macchiato-framework/macchiato-core/blob/e5ec039ad0c028736c5ecfa21c439bb217813248/src/macchiato/middleware/restful_format.cljs#L37), I guess:

```clojure
cljs.user=> (js->clj (js/JSON.parse "{\"a\": 1}") :keywordize-keys true)
{:a 1}

cljs.user=> (js->clj (js/JSON.parse "[1 2 3]") :keywordize-keys true)
Unexpected number in JSON at position 3
```

**Comment by denisidoro** [comment]
Nevermind. The problem was that I wasn't using ` -H "Accept: application/json"` in my curl command
